### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Usagib**
pull request open fo style fixing and review

### CODE REVIEW

**Comment by Usagib** [comment]
Hello guys just finished coding and correcting rubocop issues.
sneding pull request for code review
Happy coding

**Comment by shshamim63** [comment]
## Status :ambulance:  [!! Invalid !!] :ambulance: 
___
Hi @Usagib  :wave: ,
First of all you were suppose to follow Git Flow:  [production master branch + main development branch + Pull Requests from feature branches to the develop]. Now there is a strict declaration that says, if a PR doesn't follow the Git Flow it will be marked as invalid review request.
screenshot
You can check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421589/) for more clarification. 
___
### Please fix this issue and send code review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Requires changes;  status[Invalid]
 
Hi team,

This pull request won't be reviewed, you didn't adhere to gitflow methodology. 

Kindly implement the changes and submit another form for a code review. Here's the [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421589/) for reference.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by Usagib** [comment]
thank you guys, i will check the methodology and ask for a new code review.

**Pull request merged**
